### ISSUE TITLE
请问zh_giga.no_cna_cmn.prune01244.klm语言模型在哪？

### ISSUE THREAD

**Issue by LZ798** [shibing624/pycorrector#116]
Windows10+pycharm+anaconda3下安装pycorrector出错：
安装方法：下载pycorrector.zip解压之后，进入文件夹下，运行python setup.py install报错
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from pycorrector import __version__
  File "D:\program\myproject\pycorrector-master\pycorrector\__init__.py", line 5, in <module>
    from .corrector import Corrector
  File "D:\program\myproject\pycorrector-master\pycorrector\corrector.py", line 11, in <module>
    from pycorrector import config
  File "D:\program\myproject\pycorrector-master\pycorrector\config.py", line 15, in <module>
    language_model_path = os.path.join(USER_DATA_DIR, 'zh_giga.no_cna_cmn.prune01244.klm')
  File "C:\Users\10157836\Anaconda3\lib\ntpath.py", line 113, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\10157836\Anaconda3\lib\genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'WindowsPath'
我没找到zh_giga.no_cna_cmn.prune01244.klm语言模型在哪？求教怎么解决这个问题？

**Comment by shibing624** [comment]
pycorrector-0.2.1 fixed.

**Comment by LZ798** [comment]
谢谢。pip install pycorrector-0.2.1，遇到错误：Building wheel for kenlm (setup.py) ... error， error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.micosoft.com/downloads/，在安装visualcppbuildtools_full.exe时，报错安装包丢失或损坏，请问这个怎么办？

**Comment by LZ798** [comment]
谢谢，安装成功

**Comment by LZ798** [comment]
谢谢。我安装好pycorrector-0.2.1，conda list后有pycorrector               0.2.1                     <pip>，import pycorrector还是出现同样的问题：
>>> import pycorrector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\10157836\Anaconda3\lib\site-packages\pycorrector\__init__.py", line 5, in <module>
    from .corrector import Corrector
  File "C:\Users\10157836\Anaconda3\lib\site-packages\pycorrector\corrector.py", line 11, in <module>
    from pycorrector import config
  File "C:\Users\10157836\Anaconda3\lib\site-packages\pycorrector\config.py", line 15, in <module>
    language_model_path = os.path.join(USER_DATA_DIR, 'zh_giga.no_cna_cmn.prune01244.klm')
  File "C:\Users\10157836\Anaconda3\lib\ntpath.py", line 113, in join
    genericpath._check_arg_types('join', path, *paths)
  File "C:\Users\10157836\Anaconda3\lib\genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'WindowsPath'
这个怎么办呢？

**Comment by LZ798** [comment]
https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm 下载了

**Comment by shibing624** [comment]
运行程序，自动下载到~/.pycorrector/datasets/zh_giga.no_cna_cmn.prune01244.klm

**Comment by chendeming** [comment]
~：表示用户的home目录
.pycorrector: 前面的点表示是隐藏的，在osx下需要通过shift+cmd+.打开
然后把下载的文件拷贝到~/.pycorrector/datasets/
