### ISSUE TITLE
执行错误

### ISSUE THREAD

**Issue by chendeming** [shibing624/pycorrector#119]
>>> import pycorrector
>>> corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')
[  DEBUG 20191210 04:18:16 corrector:109] Loaded same pinyin file: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/data/same_pinyin.txt, same stroke file: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/data/same_stroke.txt, spend: 0.041 s.
Downloading data from https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1399, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/utils/get_file.py", line 280, in get_file
    urlretrieve(origin, fpath, dl_progress)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1360, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/corrector.py", line 224, in correct
    maybe_errors = self.detect(sentence)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/detector.py", line 334, in detect
    self.check_detector_initialized()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/detector.py", line 111, in check_detector_initialized
    self.initialize_detector()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/detector.py", line 72, in initialize_detector
    get_file(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pycorrector-0.2.1-py3.8.egg/pycorrector/utils/get_file.py", line 284, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm : None -- [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

**Comment by chendeming** [comment]
已解决。.pycorrector文件夹是隐藏的，shift+cmd+.可以显示，将下载的2.8G文件拷贝到.pycorrector/datasets文件夹下即可。

**Comment by PeterPanUnderhill** [comment]
> 已解决。.pycorrector文件夹是隐藏的，shift+cmd+.可以显示，将下载的2.8G文件拷贝到.pycorrector/datasets文件夹下即可。

请问这个路径不在...python/site-packages/下吗？

**Comment by winniechiou** [comment]
<img width="758" alt="截圖 2022-08-09 下午4 25 06" src="https://user-images.githubusercontent.com/45808477/183601437-634f7b54-3968-4184-ab35-dfab39b8b42c.png">
您好，我也遇到相同的問題，但shift+cmd+.後並沒有顯示出.pycorrector （如上圖），想請問如何解決呢？謝謝

**Comment by shibing624** [comment]
home目录下
