### ISSUE TITLE
bert_corrector.py ERROR

### ISSUE THREAD

**Issue by ykiller2012** [shibing624/pycorrector#138]
### Describe the bug
在百度网盘下载模型文件后，运行该脚本时提示
Traceback (most recent call last):
  File "D:/development/GitSpace/pycorrector/pycorrector/bert/bert_corrector.py", line 79, in <module>
    d = BertCorrector()
  File "D:/development/GitSpace/pycorrector/pycorrector/bert/bert_corrector.py", line 30, in __init__
    tokenizer=bert_model_dir)
  File "D:\Anaconda3\envs\text-corrector\lib\site-packages\transformers\pipelines.py", line 850, in pipeline
    raise KeyError("Unknown task {}, available tasks are {}".format(task, list(SUPPORTED_TASKS.keys())))
### **KeyError: "Unknown task fill-mask, available tasks are ['feature-extraction', 'sentiment-analysis', 'ner', 'question-answering']"**

**Comment by ykiller2012** [comment]
已经发现问题，为transformer模块版本的问题，安装2.4.0即可
