### ISSUE TITLE
请问modelcard.json文件不存在怎么解决？

### ISSUE THREAD

**Issue by iceelor** [shibing624/pycorrector#174]
2020-11-13 10:07:15.802585: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-13 10:07:15.810080: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "bert_corrector.py", line 79, in <module>
    d = BertCorrector()
  File "bert_corrector.py", line 29, in __init__
    tokenizer=bert_model_dir)
  File "D:\service\pycorrector\lib\site-packages\transformers\pipelines.py", line 1798, in pipeline
    modelcard = ModelCard.from_pretrained(modelcard)
  File "D:\service\pycorrector\lib\site-packages\transformers\modelcard.py", line 153, in from_pretrained
    model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies, resume_download=False
  File "D:\service\pycorrector\lib\site-packages\transformers\file_utils.py", line 269, in cached_path
    raise ValueError("unable to parse {} as a URL or as a local path".format(url_or_filename))
ValueError: unable to parse D:\workspace\project-py3\pycorrector\pycorrector\bert\../data/bert_models/chinese_finetuned_lm/modelcard.json as a URL or as a local path

**Comment by yxz-git** [comment]
我也是，兄弟解决了吗

**Comment by dage0127** [comment]
原因： 应该是transformer新版本增加了modelcard。
解决方法：
找到File "D:\service\pycorrector\lib\site-packages\transformers\pipelines.py", line 1798, in pipeline
注释掉：modelcard = ModelCard.from_pretrained(modelcard)
加上:pass

**Comment by shibing624** [comment]
代码已经更新：fix with https://github.com/shibing624/pycorrector/commit/734c0ba9c29d2bf52b58687ee3533cf9f1096a98
更新到最新版本代码即可，完成transformers代码迁移，后续不需要安装transformers。
