### ISSUE TITLE
使用ernie里面的检测器显示ernie的tokenizer缺少分词词典

### ISSUE THREAD

**Issue by GuiQuQu** [shibing624/pycorrector#240]
报错如下:
[   INFO 20211025 06:32:25 tokenizing_ernie:  86] get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[  DEBUG 20211025 06:32:25 file_utils:  56] https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz cached in C:\Users\12644\.paddle-ernie-cache
Traceback (most recent call last):
  File "D:/code/ques_match/src/rule/test2.py", line 11, in <module>
    corrector = ernie_corrector.ErnieCorrector()
  File "C:\Users\12644\anaconda3\lib\site-packages\pycorrector\ernie\ernie_corrector.py", line 50, in __init__
    self.ernie_tokenizer = ErnieTokenizer.from_pretrained(model_dir)
  File "C:\Users\12644\anaconda3\lib\site-packages\pycorrector\ernie\tokenizing_ernie.py", line 95, in from_pretrained
    raise ValueError('no vocab file in pretrain dir: %s' % pretrain_dir)
ValueError: no vocab file in pretrain dir: C:\Users\12644\.paddle-ernie-cache\466eabcffd6d6a83ae9cb97dd1a167bd

**Comment by shibing624** [comment]
paddle的版本是否跟readme要求一致？
