### ISSUE TITLE
使用cn数据集训练macbert报错，目前无法进行训练。

### ISSUE THREAD

**Issue by xiaohuzi1996** [shibing624/pycorrector#273]
[   INFO 20220506 05:40:26 train:  88] train model ...
GPU available: False, used: False
TPU available: None, using: 0 TPU cores

  | Name      | Type            | Params
----------------------------------------------
0 | bert      | BertForMaskedLM | 102 M 
1 | detection | Linear          | 769   
2 | sigmoid   | Sigmoid         | 0     
----------------------------------------------
102 M     Trainable params
0         Non-trainable params
102 M     Total params
Validation sanity check: 0it [00:00, ?it/s][   INFO 20220506 05:40:26 base_model: 110] Valid.
Validation sanity check: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.00s/it][   INFO 20220506 05:40:28 base_model: 167] loss: 0.5749217569828033
[   INFO 20220506 05:40:28 base_model: 168] Detection:
acc: 0.0000
[   INFO 20220506 05:40:28 base_model: 170] Correction:
acc: 0.0625
[   INFO 20220506 05:40:28 evaluate_util:  54] The detection result is precision=0.31343283582089554, recall=0.84 and F1=0.4565217391304348
[   INFO 20220506 05:40:28 evaluate_util:  86] The correction result is precision=0.3333333333333333, recall=0.30434782608695654 and F1=0.31818181818181823
[   INFO 20220506 05:40:28 evaluate_util: 131] Sentence Level: acc:0.062500, precision:1.000000, recall:0.062500, f1:0.117647
Epoch 0:   0%|                                                                                                                                                       | 0/293 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    main()
  File "train.py", line 98, in main
    trainer.fit(model, train_loader, valid_loader)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 62, in train
    results = self.train_or_test()
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 521, in train
    self.train_loop.run_training_epoch()
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 560, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 687, in run_training_batch
    self.training_step_and_backward(
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 806, in training_step_and_backward
    result = self.training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 330, in training_step
    training_step_output = self.trainer.accelerator_backend.training_step(args)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 74, in training_step
    return self._step(self.trainer.model.training_step, args)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 70, in _step
    output = model_step(*args)
  File "/new_data/.virtualenvs/huzhang_pycorrector/lib/python3.8/site-packages/pycorrector/macbert/base_model.py", line 130, in training_step
    self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True, logger=True, batch_size=len(ori_text))
TypeError: log() got an unexpected keyword argument 'batch_size'

训练的时候，出现以上错误。（TypeError: log() got an unexpected keyword argument 'batch_size'），这个是什么情况导致的呀。

**Comment by shibing624** [comment]
没啥影响，是pytorch_lightning的版本不一致的原因，其实更改为readme指定版本就可以。

**Comment by xiaohuzi1996** [comment]
好的。感谢回复呀，目前训练、测试都已经跑通了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shibing624/pycorrector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] 使用cn数据集训练macbert报错，目前无法进行训练。 (Issue #273)





 
没啥影响，是pytorch_lightning的版本不一致的原因，其实更改为readme指定版本就可以。
