### ISSUE TITLE
跑kenlm语言模型出错

### ISSUE THREAD

**Issue by Stan370** [shibing624/pycorrector#284]
已经下载.klm文件放到对应目录
Traceback (most recent call last):
  File "C:\Users\Stan\Desktop\中文拼写检错实验_更新版\n-gram+crf\ngram.py", line 211, in <module>
    corrected_sent, detail = model.correct('少先队员因该为老人让坐')
  File "D:\Program Files\Anaconda3\lib\site-packages\pycorrector\corrector.py", line 291, in correct
    maybe_errors, proper_details = self.detect_sentence(sentence, idx, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\pycorrector\detector.py", line 374, in detect_sentence
    self.check_detector_initialized()
  File "D:\Program Files\Anaconda3\lib\site-packages\pycorrector\detector.py", line 114, in check_detector_initialized
    self._initialize_detector()
  File "D:\Program Files\Anaconda3\lib\site-packages\pycorrector\detector.py", line 88, in _initialize_detector
    self.lm = kenlm.Model(self.language_model_path)
  File "kenlm.pyx", line 142, in kenlm.Model.__init__
OSError: Cannot read model 'C:\Users\Stan\Desktop\中文拼写检错实验_更新版\n-gram+crf\people2014corpus_chars.klm' (util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'. No such file or directory while opening C:\Users\Stan\Desktop\中文拼写检错实验_更新版\n-gram+crf\people2014corpus_chars.klm)

Traceback (most recent call last):
  File "kenlm.pyx", line 139, in kenlm.Model.__init__
RuntimeError: util\file.cc:74 in util::OpenReadOrThrow threw ErrnoException because `-1 == (ret = _open(name, 0x8000 | 0x0000))'.
No such file or directory while opening C:\Users\Stan\Desktop\中文拼写检错实验_更新版\n-gram+crf\people2014corpus_chars.klm

**Comment by shibing624** [comment]
下载readme的，还是自己训练的？自己训练的再训练一次试下。

**Comment by Stan370** [comment]
readme里下载的2014版人民日报数据训练的模型
<img width="668" alt="image" src="https://user-images.githubusercontent.com/56168768/173000956-00fad28e-9e09-4f10-8363-50e0947b0242.png">
照这个跑的

**Comment by shibing624** [comment]
路径指定正确就可以。你check下路径。

**Comment by YYTB** [comment]
路径里面有中文不行，我的也是这样
