### ISSUE TITLE
badcase记录

### ISSUE THREAD

**Issue by wangyingshuai** [shibing624/pycorrector#31]
楼主，您好！我运行您的代码，遇到如下两个badcase：
（1）为了解决召回率太高，召回本不应该召回的问题，可以把正确的不想召回的词语加入到word_freq字典，这样做确实有一部分效果，但是对于单个字的，不起作用，比如：【湿度怎样呢？水分多吗	('湿度怎样呢？水分多么', [['吗', '么', 9, 10]])】这个例子，我把“吗”加入word_freq字典，还是没有输出我想要的结果，请楼主帮忙调试代码？
(2）在word_freq中多加入几个新词，就报下面的错
2018-10-16 18:51:08,632 - /Users/wangyingshuai/pycorrector-master/pycorrector/detector.py - DEBUG - Loaded language model: /Users/wangyingshuai/pycorrector-master/pycorrector/data/kenlm/people_chars_lm.klm, spend: 0.008133888244628906 s
Traceback (most recent call last):
  File "/Users/wangyingshuai/pycorrector-master/examples/use_custom_confusion.py", line 35, in <module>
    pycorrector.set_custom_confusion_dict(path='./my_confusion.txt')
  File "/Users/wangyingshuai/pycorrector-master/pycorrector/detector.py", line 85, in set_custom_confusion_dict
    self.check_detector_initialized()
  File "/Users/wangyingshuai/pycorrector-master/pycorrector/detector.py", line 46, in check_detector_initialized
    self.initialize_detector()
  File "/Users/wangyingshuai/pycorrector-master/pycorrector/detector.py", line 36, in initialize_detector
    self.word_freq = self.load_word_freq_dict(self.word_freq_path)
  File "/Users/wangyingshuai/pycorrector-master/pycorrector/detector.py", line 57, in load_word_freq_dict
    word = info[0]
IndexError: list index out of range

**Comment by shibing624** [comment]
后续会升级一个用户自定义过滤词典。

**Comment by wangyingshuai** [comment]
嗯嗯，期待楼主早日升级，谢谢！
