### ISSUE TITLE
T5模型训练的时候会出现RuntimeError: Caught RuntimeError in replica 0 on device 0.

### ISSUE THREAD

**Issue by Candice52** [shibing624/pycorrector#314]
### Describe the Question
如题，我看t5模型训练的时候使用的是v100……我在服务器上使用的是用4个RTX 2080ti，在训练的时候只设置了CUDA_VISIBLE_DEVICES，所以训练的时候报错：

```
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    train()
  File "train.py", line 278, in train
    model_args.model_name_or_path) else None
  File "/data/jydong/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 756, in train
    tr_loss += self.training_step(model, inputs)
……
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
……
File "/data/user/anaconda3/lib/python3.7/site-packages/transformers/modeling_t5.py", line 374, in forward
    q, k.transpose(3, 2)
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 10.76 GiB total capacity; 9.49 GiB already allocated; 13.44 MiB free; 9.63 GiB reserved in total by PyTorch)
```
想问一下是在训练的时候用了多卡的话模型也要放在多卡上学习嘛？我该怎么解决呢？感谢解答小白的问题hh~😊

**Comment by shibing624** [comment]
这只是你的机器显存不够，batch_size设为8再跑。
```
python train.py --do_train --do_eval --batch_size 8 
```
