### ISSUE TITLE
使用cuda版的torch 和 GPT模型问题

### ISSUE THREAD

**Issue by winnnntttter** [shibing624/pycorrector#441]
之前我用的cpu版本的torch
``` python
print(torch.__version__)  # 2.1.1+cpu
print(torch.version.cuda)  # None

m = GptCorrector()
```
是可以加载模型的，只是速度比较慢，然后我安装cuda，和cuda版本的torch，然后报错了。

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

``` python
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')
print('Using device:', device)    # cuda
print(torch.__version__)            # 2.1.1+cu118
print(torch.version.cuda)         # 11.8

m = GptCorrector()
```
错误信息：
```
Traceback (most recent call last):
  File "E:\work\text-corrector\main-gpu.py", line 13, in <module>
    m = GptCorrector() 
  File "D:\tool\python\3-10\lib\site-packages\pycorrector\gpt\gpt_corrector.py", line 28, in __init__
    super(GptCorrector, self).__init__(
  File "D:\tool\python\3-10\lib\site-packages\pycorrector\gpt\gpt_model.py", line 137, in __init__
    self.model = model_class.from_pretrained(
  File "D:\tool\python\3-10\lib\site-packages\transformers\models\auto\auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "D:\tool\python\3-10\lib\site-packages\transformers\modeling_utils.py", line 3480, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\tool\python\3-10\lib\site-packages\transformers\modeling_utils.py", line 3601, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.
```

请问如何解决呢

**Comment by shibing624** [comment]
pip install safetensors

**Comment by winnnntttter** [comment]
> pip install safetensors

没有用，已经安装过了，换成2.1.1+cpu版的torch就没问题，2.1.1+cu118的就有问题

**Comment by shibing624** [comment]
我不清楚你的环境问题，可能你的显存不够，需要用cpu加载部分权重，建议用24G以上显存。

**Comment by winnnntttter** [comment]
我继续使用macbert模型了，不尝试GPT模型了
