### ISSUE TITLE
chatglm训练时发生的问题，烦请解答！

### ISSUE THREAD

**Issue by GaoYang-debug** [shibing624/pycorrector#445]
### Describe the Question
Please provide a clear and concise description of what the question is.
运行python training_chatglm_demo.py --do_train --do_predict

使用examples/data/garmmar中的train、test数据

报错：
 
Traceback (most recent call last):
  File "training_chatglm_demo.py", line 76, in <module>
    main()
  File "training_chatglm_demo.py", line 58, in main
    model.train_model(args.train_file, eval_data=args.test_file)
  File "/data1/gy/Miniconda3/envs/pycorrector/lib/python3.8/site-packages/pycorrector/gpt/gpt_model.py", line 416, in train_model
    eval_dataset = self.load_and_cache_examples(eval_data, evaluate=True)
  File "/data1/gy/Miniconda3/envs/pycorrector/lib/python3.8/site-packages/pycorrector/gpt/gpt_model.py", line 655, in load_and_cache_examples
    return GptSupervisedDataset(tokenizer, args, data, mode)
  File "/data1/gy/Miniconda3/envs/pycorrector/lib/python3.8/site-packages/pycorrector/gpt/gpt_utils.py", line 582, in __init__
    or (mode == "dev" and args.use_cached_eval_features and not args.no_cache)
**AttributeError: 'GptArgs' object has no attribute 'use_cached_eval_features'**

请问GptArgs的use_cached_eval_features模块在哪里，我在GptArgs类下并没有找到。烦请解答谢谢！

**Comment by shibing624** [comment]
fixed.

**Comment by GaoYang-debug** [comment]
谢谢您
---- 回复的原邮件 ----
| 发件人 | Ming Xu ***@***.***> |
| 发送日期 | 2023年11月28日 15:44 |
| 收件人 | shibing624/pycorrector ***@***.***> |
| 抄送人 | Yang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [shibing624/pycorrector] chatglm训练时发生的问题，烦请解答！ (Issue #445) |

fixed.

**Comment by huangChengz** [comment]
我也遇到这个问题了求解答 谢谢大佬

**Comment by shibing624** [comment]
更新代码后，还有问题吗？
