### ISSUE TITLE
使用Dockerfile构建镜像时step7/12报错

### ISSUE THREAD

**Issue by XtremeW** [shibing624/pycorrector#462]
Step 7/12 : RUN pip3 install https://github.com/kpu/kenlm/archive/master.zip
 ---> Running in 77a5768775e5

WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting https://github.com/kpu/kenlm/archive/master.zip
  Downloading https://github.com/kpu/kenlm/archive/master.zip (553kB)
Installing collected packages: kenlm
  Running setup.py install for kenlm: started
    Running setup.py install for kenlm: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-yr7yljb_-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5tc29uwg-record/install-record.txt --single-version-externally-managed --compile:
    Will build with KenLM max_order set to 6
    running install
    running build
    running build_ext
    CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
      CMake 3.1 or higher is required.  You are running version 2.8.12.2
    
    
    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-yr7yljb_-build/setup.py", line 129, in <module>
        include_package_data=True,
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-yr7yljb_-build/setup.py", line 105, in run
        ["cmake", source_dir] + cmake_args, cwd=self.build_temp, env=env
      File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-yr7yljb_-build', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-yr7yljb_-build/build/lib.linux-x86_64-3.6', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_PYTHON_STANDALONE=ON', '-DKENLM_MAX_ORDER=6', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-yr7yljb_-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-5tc29uwg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-yr7yljb_-build/
The command '/bin/sh -c pip3 install https://github.com/kpu/kenlm/archive/master.zip' returned a non-zero code: 1

我尝试了很多办法都没有解决

**Comment by shibing624** [comment]
改下： RUN pip3 install kenlm

**Comment by shibing624** [comment]
fixed. build with python3.8 and pip install kenlm==0.1.0
