### ISSUE TITLE
使用pip install -U pycorrector安装pycorrector最新版本后，测试运行报错

### ISSUE THREAD

**Issue by sovereign-stone** [shibing624/pycorrector#486]
- ubuntu

from pycorrector import T5Corrector

m = T5Corrector()
res = m.correct_batch(['今天新情很好', '你找到你最喜欢的工作，我也很高心。'])
print(res)

- 报错：

Traceback (most recent call last):
  File "/home/soc/gitcode/github/machine_learning/corrector_text/pycorrector.py", line 3, in <module>
    from pycorrector import T5Corrector
  File "/home/soc/gitcode/github/machine_learning/corrector_text/pycorrector.py", line 3, in <module>
    from pycorrector import T5Corrector
ImportError: cannot import name 'T5Corrector' from partially initialized module 'pycorrector' (most likely due to a circular import) (/home/soc/gitcode/github/machine_learning/corrector_text/pycorrector.py)

- pip show pycorrector

Name: pycorrector
Version: 1.0.4
Summary: Chinese Text Error Corrector
Home-page: https://github.com/shibing624/pycorrector
Author: XuMing
Author-email: xuming624@qq.com
License: Apache 2.0
Location: /home/******/machine_learn/lib/python3.8/site-packages
Requires: datasets, jieba, loguru, numpy, pandas, pypinyin, six, transformers
Required-by: 

- 我在安装完pycorrector后，初次运行就报错循环引用，我想请问一下这是什么原因导致的，应该怎么修改

**Comment by sovereign-stone** [comment]
已解决！
