### ISSUE TITLE
seq2seq MemoryError

### ISSUE THREAD

**Issue by Weirdo233** [shibing624/pycorrector#62]
仅使用CGED17训练的时候，报错：
```
Traceback (most recent call last):
  File "D:/Github/pycorrector/pycorrector/seq2seq/train.py", line 105, in <module>
    rnn_hidden_dim=config.rnn_hidden_dim)
  File "D:/Github/pycorrector/pycorrector/seq2seq/train.py", line 52, in train
    encoder_input_data = np.zeros((len(input_texts), max_input_texts_len, len(input_token_index)), dtype='float32')
```
按理说数据集只有3w内存应该不会爆啊，请问有没有什么解决方案

**Comment by shibing624** [comment]
适当修改参数，max_input_texts_len, word_emb_size, word_size 改小点，都有帮助。

**Comment by liuhuihuii** [comment]
the same question,具体数值有什么建议吗，谢谢

**Comment by shibing624** [comment]
按推荐的默认参数，我本地都测试过。
