### ISSUE TITLE
RuntimeError: index out of range at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:193

### ISSUE THREAD

**Issue by OctHex2016** [shibing624/pycorrector#87]
我之后预到一个新问题，我执行finetune_on_pregenerated.py时预到以下情况：
我应如何解决？之前我尝试在改max_seq_len 做512 都不行，求解，谢谢！
Traceback (most recent call last):
  File "finetune_on_pregenerated.py", line 330, in <module>
    main()
  File "finetune_on_pregenerated.py", line 300, in main
    outputs = model(input_ids, segment_ids, input_mask, lm_label_ids, is_next)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 778, in forward
    attention_mask=attention_mask, head_mask=head_mask)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 706, in forward
    embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pytorch_transformers/modeling_bert.py", line 264, in forward
    words_embeddings = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at ../aten/src/TH/generic/THTensorEvenMoreMath.cpp:193

**Comment by 932515687** [comment]
我也遇到了这个问题，怎末解决的呢
