### ISSUE TITLE
Colab 用GPU 的状况

### ISSUE THREAD

**Issue by OctHex2016** [shibing624/pycorrector#89]
我刚刚在Colab 用GPU 行看到一些问题希望指教，谢谢。
我首先行了以下的指令：
!python pregenerate_training_data.py --train_corpus '/content/drive/My Drive/Colab Notebooks/a20.txt' --bert_model bert-base-chinese --do_lower_case --output_dir '/content/drive/My Drive/Colab Notebooks/ training' --epochs_to_generate 3 --max_seq_len 512

然后再Finetune 以 pregenerated 的资料，并发现以下问题。

!export CUDA_VISIBLE_DEVICES=0,1,2

RuntimeError: CUDA error: device-side assert triggered

**Comment by shibing624** [comment]
没描述清楚问题吧？GPU有几个，写几个，写清楚对应id，测试时用export CUDA_VISIBLE_DEVICES=0

**Comment by OctHex2016** [comment]
> 没描述清楚问题吧？GPU有几个，写几个，写清楚对应id，测试时用export CUDA_VISIBLE_DEVICES=0

谢谢回覆，GPU有1个，并改了CUDA_VISIBLE_DEVICES=0

<img width="816" alt="螢幕截圖 2019-08-13 上午10 38 36" src="https://user-images.githubusercontent.com/20900066/62911412-dd89bd80-bdb6-11e9-83ff-dd0c258c8258.png">

**Comment by OctHex2016** [comment]
> 没描述清楚问题吧？GPU有几个，写几个，写清楚对应id，测试时用export CUDA_VISIBLE_DEVICES=0

还是遇到相同情况：

Training examples: 100% 280277/280277 [02:39<00:00, 1755.32it/s]
2019-08-13 02:54:52,339: Loading complete!
Epoch 0:   2% 841/35035 [15:52<10:45:38,  1.13s/it, Loss: 5.36243]/pytorch/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [76,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

Traceback (most recent call last):
  File "finetune_on_pregenerated.py", line 330, in <module>
    main()
  File "finetune_on_pregenerated.py", line 300, in main
    outputs = model(input_ids, segment_ids, input_mask, lm_label_ids, is_next)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 778, in forward
    attention_mask=attention_mask, head_mask=head_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 706, in forward
    embedding_output = self.embeddings(input_ids, position_ids=position_ids, token_type_ids=token_type_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_transformers/modeling_bert.py", line 265, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered

**Comment by OctHex2016** [comment]
@shibing624 想问会否我的语料每一行的字粒数量超出了max_seq_len？

**Comment by shibing624** [comment]
建议处理一下语料，参数多调试几组，自己动手，多学多懂。

**Comment by HonayKing** [comment]
@OctHex2016 
能否提供下pregenerate_training_data.py 和 finetune_on_pregenerated.py 这两个fune-tine文件，我这边没找到... ...
//谢谢！

**Comment by OctHex2016** [comment]
> @OctHex2016
> 能否提供下pregenerate_training_data.py 和 finetune_on_pregenerated.py 这两个fune-tine文件，我这边没找到... ...
> //谢谢！

https://github.com/huggingface/pytorch-transformers.git
