### ISSUE TITLE
一个编译会出错的地方：UnicodeDecodeError: 'ascii' codec can't decode 

### ISSUE THREAD

**Issue by JohnParken** [shibing624/pycorrector#94]
Traceback (most recent call last):   File "setup.py", line 16, in <module>     readme = f.read()   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode     
return codecs.ascii_decode(input, self.errors)[0] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 20: ordinal not in range(128)

运行python3 setup.py install 进行编译的时候偶尔汇报这个错误，把setup.py15行中 f = open（）那里加上encoding=‘utf-8’就可以。

**Comment by shibing624** [comment]
fixed.
